appPosto/Models/ErrorViewModel.cs
namespace appPosto.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

appPosto/Models/HomeModel.cs
namespace appPosto.Models
{
    public class HomeModel
    {
        public string Nome { get; set; }

        public string Email { get; set; }
    }
}

appPosto/Models/PostosModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace appPosto.Models
{
    public class PostosModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome do posto")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Digite o endereço do posto")]
        public string Endereco { get; set; }

        [Required(ErrorMessage = "Digite o preço da gasolina comum do posto")]
        public float PrecoGasolinaComum { get; set; }

        [Required(ErrorMessage = "Digite o preço da gasolina aditivada")]
        public float PrecoGasolinaAditivada { get; set; }

        [Required(ErrorMessage = "Digite o preço do Diesel")]
        public float PrecoDiesel { get; set; }

        //nota: Os preços podem ser setados como 0, mas nunca como nulos. O usuário obrigatoriamente precisa informar ao sistema os valores e, caso inexistentes, colocar como 0.
    }
}

appPosto/Controllers/HomeController.cs
using appPosto.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace appPosto.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

appPosto/Controllers/PostosController.cs
using appPosto.Models;
using appPosto.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace appPosto.Controllers
{
    public class PostosController : Controller
    {
        private readonly IPostosRepositorio _postosRepositorio;

        public PostosController(IPostosRepositorio postosRepositorio)
        {
            _postosRepositorio = postosRepositorio;   
        }
        public IActionResult Index()
        {
            List<PostosModel> postos = _postosRepositorio.BuscarTodos();
            
            return View(postos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            PostosModel posto = _postosRepositorio.ListarPorId(id);
            return View(posto);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            PostosModel posto = _postosRepositorio.ListarPorId(id);
            return View(posto);
        }

        public IActionResult Apagar (int id)
        {
            try
            {
                bool apagado = _postosRepositorio.Apagar(id);

                if (apagado)
                {
                   TempData["MensagemSucesso"] = "Posto apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato, tente novamente.";
                }

                return RedirectToAction("Index");
            }
            catch (Exception erro) {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu contato, tente novamente. Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(PostosModel postos)
        {
            try 
            {
                if (ModelState.IsValid)
                {
                    _postosRepositorio.Adicionar(postos);
                    TempData["MensagemSucesso"] = "Posto cadastrado com sucesso!" ;
                    return RedirectToAction("Index");

                }

                return View(postos);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu contato, tente novamente. Detalhe do erro: {erro.Message}" ;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(PostosModel postos)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _postosRepositorio.Atualizar(postos);
                    TempData["MensagemSucesso"] = "Posto alterado com sucesso!" ;
                    return RedirectToAction("Index");
                }

                return View("Editar", postos);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar seu contato, tente novamente. Detalhe do erro: {erro.Message}" ;
                return View("Editar", postos);
            }
        }

    }
}

appPosto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Sistema de controle de Postos</p>
</div>

appPosto/Views/Postos/ApagarConfirmacao.cshtml
@model PostosModel
@{
    ViewData["Title"] = "Confirmação de apagar o posto";
}

<div class="text-center">
    <h3>Realmente deseja apagar o posto (@Model.Nome)</h3>
</div>

<div class="text-center">
    <a role="button" class="btn btn-primary" asp-controller="Postos" asp-action="Index">Cancelar</a>
    <a role="button" class="btn btn-danger" asp-controller="Postos" asp-route-id="@Model.Id" asp-action="Apagar">Confirmar</a>
</div>

appPosto/Views/Postos/Criar.cshtml
@model PostosModel
@{
    ViewData["Title"] = "Adicionar Posto";
}

<div class="text-center">
   
    <h1>Cadastrar Contato</h1>

</div>

    <form asp-controller="Postos" asp-action="Criar" method="post">
        <div class="mb-3">
            <label for="nome-posto" class="form-label">Posto</label>
            <input type="text" asp-for="Nome" class="form-control" placeholder="Insira o nome do posto..">
            @Html.ValidationMessageFor(x => x.Nome)
        </div>

        <div class="mb-3">
            <label for="endereco-posto" class="form-label">Endereco</label>
        <input type="text" asp-for="Endereco" class="form-control" placeholder="Insira o endereço..">
        @Html.ValidationMessageFor(x => x.Endereco)
        </div>

        <div class="mb-3">
            <label for="preco-gasolina-comum" class="form-label">Gasolina Comum</label>
        <input type="text" asp-for="PrecoGasolinaComum" class="form-control" placeholder="Insira o valor da gasolina comum nesse posto..">
        @Html.ValidationMessageFor(x => x.PrecoGasolinaComum)
        </div>

        <div class="mb-3">
            <label for="preco-gasolina-aditivada" class="form-label">Gasolina Aditivada</label>
        <input type="text" asp-for="PrecoGasolinaAditivada" class="form-control" placeholder="Insira o valor da gasolina aditivada nesse posto..">
        @Html.ValidationMessageFor(x => x.PrecoGasolinaAditivada)
        </div>

        <div class="mb-3">
            <label for="preco-diesel" class="form-label">Diesel</label>
        <input type="text" asp-for="PrecoDiesel" class="form-control" placeholder="Insira o valor do diesel nesse posto..">
        @Html.ValidationMessageFor(x => x.PrecoDiesel)
        </div>


        <button type="submit" class="btn btn-primary">Adicionar</button>
        <a role="button" class="btn btn-secondary" asp-controller="Postos" asp-action="Index">Voltar</a>
    </form>

appPosto/Views/Postos/Editar.cshtml
@model PostosModel
@{
    ViewData["Title"] = "Editar Posto";
}

<div class="text-center">

    <h1>Editar Posto</h1>

</div>

<form asp-controller="Postos" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label for="nome-posto" class="form-label">Posto</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Insira o nome do posto..">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="mb-3">
        <label for="endereco-posto" class="form-label">Endereco</label>
        <input type="text" asp-for="Endereco" class="form-control" placeholder="Insira o endereço..">
        @Html.ValidationMessageFor(x => x.Endereco)
    </div>

    <div class="mb-3">
        <label for="preco-gasolina-comum" class="form-label">Gasolina Comum</label>
        <input type="text" asp-for="PrecoGasolinaComum" class="form-control" placeholder="Insira o valor da gasolina comum nesse posto..">
    </div>

    <div class="mb-3">
        <label for="preco-gasolina-aditivada" class="form-label">Gasolina Aditivada</label>
        <input type="text" asp-for="PrecoGasolinaAditivada" class="form-control" placeholder="Insira o valor da gasolina aditivada nesse posto..">
    </div>

    <div class="mb-3">
        <label for="preco-diesel" class="form-label">Diesel</label>
        <input type="text" asp-for="PrecoDiesel" class="form-control" placeholder="Insira o valor do diesel nesse posto..">
    </div>


    <button type="submit" class="btn btn-primary">Editar</button>
    <a role="button" class="btn btn-secondary" asp-controller="Postos" asp-action="Index">Voltar</a>
</form>

appPosto/Views/Postos/Index.cshtml
@model List<PostosModel>
@{
    ViewData["Title"] = "Listagem de Postos";
}
<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a role="button" class="btn btn-primary" asp-controller="Postos" asp-action="Criar">Adicionar novo posto</a>
    </div>

    <br />

    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

   

    @if(TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Listagem de Postos</h1>

    <table class="table" id="table-postos">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Posto</th>
                <th scope="col">Endereço</th>
                <th scope="col">Gasolina Normal</th>
                <th scope="col">Gasolina Aditivada</th>
                <th scope="col">Diesel</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any())
            {
                foreach(PostosModel postos in Model)
                {
                    <tr>
                        <th scope="row">@postos.Id</th>
                        <td>@postos.Nome</td>
                        <td>@postos.Endereco</td>
                        <td>@postos.PrecoGasolinaComum</td>
                        <td>@postos.PrecoGasolinaAditivada</td>
                        <td>@postos.PrecoDiesel</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@postos.Id" asp-controller="Postos" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@postos.Id" asp-controller="Postos" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

appPosto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - appPosto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/appPosto.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">appPosto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="postos" asp-action="Index">Controle de Postos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - appPosto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.4/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>